### ISSUE TITLE
Automatic builds

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/JuliaDynamics#1]
@jaredhowland Since I do not know how to build the website locally (please share a link/knowledge how to), is it possible to get the automatic building working? GitHub states that the problem is a symlink:

https://help.github.com/articles/page-build-failed-file-is-a-symlink/

**Comment by Datseris** [comment]
More specific message: 

>  Your site is having problems building: A file was included in src/index.html that is a symlink or does not exist in your _includes directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.

**Comment by jaredhowland** [comment]
I have played around with it and can't immediately see where the symlink is coming from. I spent about 5 or 10 minutes on it. In my experience, it is sometimes easiest, and provides more flexibility, to build it on your local machine and push the site to Github.

Github pages just uses Jekyll so there is extensive documentation on how to get Jekyll running on your local machine there: <https://jekyllrb.com/docs/>

You can build the site and then push to a Github repository. Otherwise, there is going to be a lot more troubleshooting. Building locally, you can use a lot more Jekyll plugins that may come in handy later that aren't allowed in an automated Github pages build. I can walk you through getting that going if you have problems but I think that will be easier than tracking down a random symlink that my local system tells me is a real file.

Would that work for you?

**Comment by Datseris** [comment]
Hi Jared,

Okay for now seems like this is the only way we can go at. You shouldn't spend any time for this, just the minimal time required until I can take over. I read the documentation, seems easy, even though I have never used Ruby or Jekyll. I thank you for your offer to help; if I run into trouble I will ask but it will probably be fine!

I do have a question: where is this site hosted? I assume that the current version of the repo does have a built state. I thought that it would use the standard GitHub link: https://juliadynamics.github.io/JuliaDynamics/ 

but the above is not the actual website. Could you please share the hosted link? If it is not yet hosted, could you please do a push that will make the hosting happen, simply so that I have a frame of reference while I am learning how to do all this? 

---

I'll leave this issue open so in the future I can consider how to do this automatically with push commits.

**Comment by jaredhowland** [comment]
You can keep all the files I've sent in the `master` repository and add the `build` directory to your `.gitignore` file. Sync the `master` branch.

Create a new branch and name it whatever you like (`gh-pages` or `documentation` or whatever). Build the site locally on your machine and push the *contents* of just the `build` directory to the new branch.

Then you can go to the settings of the whole repository and under the main `Options` section scroll down to `GitHub Pages`. There you can select the branch you want GitHub to serve a static website from. Select your new branch, and hit save. *Do not* select a theme or it will override the files you have generated. I personally also select "Enforce HTTPS" but you do what you want there.

Give it maybe 5 minutes and then it should serve the site from the expected URL (`https://username.github.io/repository` which should be <https://juliadynamics.github.io/juliadynamics>).

**Comment by Datseris** [comment]
At the moment I can't get it to work... I have been following the instructions from the page you linked. I then have a local copy of the repo in my drive and in my power-shell I try to do:
```
PS C:\Users\datseris\JuliaDynamics> gem install bundler
Successfully installed bundler-2.0.1
Parsing documentation for bundler-2.0.1
Done installing documentation for bundler after 3 seconds
1 gem installed
PS C:\Users\datseris\JuliaDynamics> bundle exec jekyll serve
Traceback (most recent call last):
        2: from C:/Ruby25-x64/bin/bundle:23:in `<main>'
        1: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
C:/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bun
dle (Gem::GemNotFoundException)
PS C:\Users\datseris\JuliaDynamics>
```

**Comment by jaredhowland** [comment]
This is likely because of a version difference between what is loaded on your machine and what is in the Gemfile.lock file in the repository. See https://stackoverflow.com/a/54038218 for possible solutions (install the version of the `bundle` gem in the Gemfile.lock file or updated the Gemfile.lock file to the version you have loaded). That should do the trick.

**Comment by Datseris** [comment]
Awesome, I have found the non existing file that is a symlink:
```
Configuration file: C:/Users/datseris/JuliaDynamics/_config.yml
            Source: C:/Users/datseris/JuliaDynamics
       Destination: C:/Users/datseris/JuliaDynamics/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Liquid Exception: Could not locate the included file 'codesnippet.html' in any of ["C:/Users/datseris/JuliaDynamics/_i
ncludes", "C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/minima-2.5.0/_includes"]. Ensure it exists in one of those directories
 and, if it is a symlink, does not point outside your site source. in src/index.html
jekyll 3.8.5 | Error:  Could not locate the included file 'codesnippet.html' in any of ["C:/Users/datseris/JuliaDynamics
/_includes", "C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/minima-2.5.0/_includes"]. Ensure it exists in one of those director
ies and, if it is a symlink, does not point outside your site source.
PS C:\Users\datseris\JuliaDynamics>
```

My `src/_codesnippets/` directory has only a `make.jl` (which I will delete because I don't want to use Julia to build the webpage). I can see that there is the file `src/_includes/codesnippet.html` though. But I don't know what to do with it :P 

What do I have to change in `index.html`? It just seems to load `codesnippet.html` in lines 107.

**Comment by jaredhowland** [comment]
You made some significant changes to `_config.yml` that stopped some errors (`symlink`) and created others (not locating `codesnippet.html`). I created a new `dev` [branch](https://github.com/JuliaDynamics/JuliaDynamics/tree/dev) that I think fixes all of them (or most of them). Try building locally using the `dev` branch and see if that fixes some of the issues. If the `benchmarks/` or `cite/` directories don't work locally, they should once they are loaded on Github.

I added a variable `site` to `_config.yml` that is a hard link to the Github-built page so links will attempt to link to the Github version rather than the local version. But if you can build `dev` locally and the home page runs fine, then you should be good to push `dev` to `master` and have things build without errors.

It also looks like you have set the repository to use the `minima` theme. That should be changed because you have created your own theme for the site. I removed that variable from your `_config.yml` on `dev` but it should be changed in the repository settings as well.

In any case, it looks like you have done some solid Jekyll homework and should be ready to start building things out from there unless you run into other build problems.

**Comment by Datseris** [comment]
Awesome thanks a lot Jared!

I have to admit I actually made none of these changes myself; they were made automatically from Jekyll! But thanks so much for making the changes you did! The website now builds and is hosted online!!! Wooohooooooo

I have already started making the changes I want and they are reflected online!!! Awesome!!!

One last comment: Let's say I decided that I **do not want the extra pages** like e.g. Benchmarks, Cite, etc. Or I want to modify them / change their title on the main page / add new ones. Where are these files actually defined? I can see that there is both `benchmarks.html` and the folder `_benchmarks` yet I can't see where the `benchmark` files are _actually included_ into the website. `config.yml` doesn't really have anything. 

What is the "include these files" file?

**Comment by jaredhowland** [comment]
The `benchmarks.html` and `cite.html` files have a `permalink` variable defined in the header of their files. This tells Jekyll where to place the file. To get rid of them, delete those `.html` files and updated your `_includes/navigation.html` file to not include them in your navigation bar. The `navigation.html` file is also where you would change their names in the navigation. You can create any `.html` file you want, give it any `permalink` variable in the header you want and it will land at that permalink from your base URL, and call it anything you want from your navigation include.

That help?

**Comment by Datseris** [comment]
Perfect thanks!
